apiVersion: apps/v1
kind: Deployment
metadata:
    name: app-deploy
    labels:
      tier: front-end
      app: nginx
      type: deploy-type

spec:
    selector:
      matchLabels:
        app: app-deployment
    replicas: 6
    template:
      metadata:
        name: pod-nginx
        labels:
          app: app-deployment
          tier: front-end
      spec:
        containers:
          - name: nginx-container
            image: nginx
