# This Storage Class will allows us to use Azure Disks with ZRS
# allowing for compatiblity between Nodes in a given AV Zone,
# and Deployment - Pods using Volumes with Azure Disks getting rescheduled

allowVolumeExpansion: true
apiVersion: storage.k8s.io.v1
kind: StorageClass
metadata:
  name: managed-csi-zrs
parameters:
  skuname: StandardSSD_ZRS
provisioner: disk.csi.azure.com
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
